CREATE TABLE IF NOT EXISTS `spray_paintings` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `identifier` VARCHAR(60) NOT NULL COMMENT 'Player citizenid or identifier',
    `player_name` VARCHAR(100) DEFAULT 'Unknown',
    `corners` JSON NOT NULL COMMENT 'Four corner world coordinates {topLeft, topRight, bottomLeft, bottomRight}',
    `normal` JSON NOT NULL COMMENT 'Surface normal vector {x, y, z}',
    `stroke_data` LONGTEXT NOT NULL COMMENT 'JSON array of all strokes including erase strokes',
    `canvas_width` INT(11) NOT NULL DEFAULT 1024,
    `canvas_height` INT(11) NOT NULL DEFAULT 1024,
    `world_x` FLOAT NOT NULL COMMENT 'Center X coordinate for proximity queries',
    `world_y` FLOAT NOT NULL COMMENT 'Center Y coordinate for proximity queries',
    `world_z` FLOAT NOT NULL COMMENT 'Center Z coordinate for proximity queries',
    `stroke_count` INT(11) NOT NULL DEFAULT 0,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `expires_at` DATETIME DEFAULT NULL COMMENT 'NULL = permanent, otherwise auto-deleted after this time',
    PRIMARY KEY (`id`),
    INDEX `idx_world_coords` (`world_x`, `world_y`, `world_z`),
    INDEX `idx_identifier` (`identifier`),
    INDEX `idx_expires_at` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
